name: Bug Report
description: Report a bug in Buff
labels: ["bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Provide steps and expected behavior.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version/Commit
      description: Git SHA or tag
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Relevant logs or stack traces
