name: Feature request
description: Propose a scoped enhancement
title: "feature: "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem / need
      description: What problem are you trying to solve?
    validations:
      required: true
  - type: textarea
    id: scope
    attributes:
      label: Scope
      description: What is in scope and what changes are expected?
    validations:
      required: true
  - type: checkboxes
    id: non_goals
    attributes:
      label: Non-goals / red-lines
      description: These must remain true
      options:
        - label: No price prediction
          required: true
        - label: No buy/sell signals
          required: true
        - label: No strategy invention/optimization
          required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: Define how we know the work is done
    validations:
      required: true