name: Milestone Task
description: Track a milestone task
labels: ["milestone"]
body:
  - type: input
    id: milestone
    attributes:
      label: Milestone
      description: e.g., M5, Phase 1(B)
    validations:
      required: true
  - type: textarea
    id: scope
    attributes:
      label: Scope
      description: What needs to be delivered?
    validations:
      required: true
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: Tests added/updated
        - label: Docs updated
        - label: Safety review done
