from __future__ import annotations

from strategies.builtins.mean_reversion import (
    BOLLINGER_REVERSION,
    KELTNER_REVERSION,
    RSI_MEAN_REVERSION,
    ZSCORE_REVERSION,
)
from strategies.builtins.momentum import MACD_MOMENTUM, ROC_MOMENTUM, STOCHASTIC_MOMENTUM
from strategies.builtins.structure import PIVOT_BREAKOUT, SR_RETEST_RULE_BASED
from strategies.builtins.trend import (
    ADX_FILTERED_BREAKOUT,
    BOLLINGER_BREAKOUT,
    DONCHIAN_BREAKOUT,
    EMA_CROSSOVER,
    SMA_CROSSOVER,
    SUPERTREND_TREND_FOLLOW,
)
from strategies.builtins.volatility import ATR_VOLATILITY_BREAKOUT, BB_KELTNER_SQUEEZE_RELEASE
from strategies.builtins.wrappers import (
    FIXED_RR_STOP_TARGET_WRAPPER,
    TIME_BASED_EXIT_WRAPPER,
    TRAILING_STOP_WRAPPER,
)

BUILTIN_STRATEGIES = [
    SMA_CROSSOVER,
    EMA_CROSSOVER,
    DONCHIAN_BREAKOUT,
    BOLLINGER_BREAKOUT,
    SUPERTREND_TREND_FOLLOW,
    ADX_FILTERED_BREAKOUT,
    RSI_MEAN_REVERSION,
    BOLLINGER_REVERSION,
    ZSCORE_REVERSION,
    KELTNER_REVERSION,
    MACD_MOMENTUM,
    ROC_MOMENTUM,
    STOCHASTIC_MOMENTUM,
    ATR_VOLATILITY_BREAKOUT,
    BB_KELTNER_SQUEEZE_RELEASE,
    PIVOT_BREAKOUT,
    SR_RETEST_RULE_BASED,
    TIME_BASED_EXIT_WRAPPER,
    TRAILING_STOP_WRAPPER,
    FIXED_RR_STOP_TARGET_WRAPPER,
]

__all__ = ["BUILTIN_STRATEGIES"]
